/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abdebatepro;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author marielmcneil
 */
public class Account extends javax.swing.JDialog {
     PreparedStatement pstmt;
    public Connection c1;
    public Statement stmt;
    public String user, email, temporaryPass,confirmPass;
//    String someUser, somePass, currentPassword, newPassword, passwordConfirmed;

    /**
     * Creates new form Accounts
     */
    public Account(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
      public void setupDB() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            c1 = DriverManager.getConnection(ABDebatePro.DBURL);
            stmt = c1.createStatement();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        updateAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        updateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abdebatepro/deleteIcon.png"))); // NOI18N
        updateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Create Account");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Remove Account");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Manage Referees");

        createAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abdebatepro/createUser_1.jpg"))); // NOI18N
        createAccount.setToolTipText("");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(135, 135, 135))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addComponent(createAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(updateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        // TODO add your handling code here:
//         JTextField userInput = new JTextField(10);
//        JTextField emailInput = new JTextField(10);
//        JPasswordField TempPasswordInput = new JPasswordField(10);
//        JPasswordField TempPasswordConfirmInput = new JPasswordField(10);
//
//        JPanel myPanel = new JPanel();
//        GridLayout layout = new GridLayout(4, 2, 0, 0);
//
//        myPanel.add(new JLabel("Username:"));
//        myPanel.add(userInput);
//        myPanel.add(new JLabel("Email:"));
//        myPanel.add(emailInput);
//        myPanel.add(new JLabel("Temporary Password:"));
//        myPanel.add(TempPasswordInput);
//        myPanel.add(new JLabel("Confirm Temporary Password:"));
//        myPanel.add( TempPasswordConfirmInput);
//        myPanel.setLayout(layout);
        JTextField userInput = new JTextField(10);
        JTextField emailInput = new JTextField(10);
        JPasswordField temporaryPasswordInput = new JPasswordField(10);
        JPasswordField PasswordConfirmInput = new JPasswordField(10);

        JPanel myPanel = new JPanel();
        GridLayout layout = new GridLayout(4, 2, 0, 0);
        
        myPanel.add(new JLabel("Username:"));
        myPanel.add(userInput);
        myPanel.add(new JLabel("E-mail:"));
        myPanel.add(emailInput);
        myPanel.add(new JLabel("Temporary Password:"));
        myPanel.add(temporaryPasswordInput);
        myPanel.add(new JLabel("Confirm Password:"));
        myPanel.add(PasswordConfirmInput);
        myPanel.setLayout(layout);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Account Management", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            user = userInput.getText();
            email = emailInput.getText();
            temporaryPass = temporaryPasswordInput.getText();
            confirmPass = PasswordConfirmInput.getText();
            Logins l1 = new Logins();
           l1.insertDB(user, confirmPass,"Referee" , email);
           l1.selectDB();
           JOptionPane.showMessageDialog(null, "Insert Successfull");
        }
        else {
            JOptionPane.showMessageDialog(null, "Insert Failed");
        }


    }//GEN-LAST:event_createAccountActionPerformed

    private void updateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountActionPerformed
        JTextField deleteUsername = new JTextField(10);
        JPanel myPanel = new JPanel();
        GridLayout layout = new GridLayout(4, 2, 0, 0);
        myPanel.add(new JLabel("Username:"));
        myPanel.add(deleteUsername);
        
         int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Remove User", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            
        Logins deleteMethod = new Logins();
        deleteMethod.deleteDB(deleteUsername.getText());
        JOptionPane.showMessageDialog(null, "Delete Successfull");
        }
        else {
            JOptionPane.showMessageDialog(null, "Delete Failed");
        }
        
        
    }//GEN-LAST:event_updateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account dialog = new Account(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton updateAccount;
    // End of variables declaration//GEN-END:variables
}
