package abdebatepro;
//========================== Imports =========================================//
import static abdebatepro.ABDebatePro.DBURL;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class MainPanel extends javax.swing.JPanel {
    //========================== Declarations ==================================
    public String user, pass;
    public Connection c1;
    public Statement stmt;
    ResultSet rs;
    String someUser, somePass;
    public String sqlStatement = "select * from Schedule Order by MatchNumber ASC";
    Algorithm a = new Algorithm();
    public int noOfWeeks;
    //========================== Constructor ===================================
    public MainPanel() {
        try {
            /*/UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            //int greenColorValue = Color.parseColor("#00ff00");
            UIManager.put("nimbusBase", Color.ORANGE);
            UIManager.put("text", Color.BLUE);
            UIManager.put("Panel.background", Color.BLACK);
            //UIManager.put("nimbusBlueGrey", new Color(255,255,255));//white
            UIManager.put("control",Color.BLACK);
            UIManager.put("TextField.background",Color.BLACK);
            //UIManager.put("textHighlight", Color.ORANGE);//black
               //UIManager.put( "textBackground", new Color(23,168,235));
               //UIManager.put("Menu.foreground", Color.RED);*/
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            //UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel(new SyntheticaSilverMoonLookAndFeel());
            //BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.FrameBorderStyle.osLookAndFeelDecorated;
        } catch (Exception e) {
            System.out.println(e);
        }
        initComponents();
        setupDB();
        //bottomPanel.setVisible(false);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        TableModel tableModel = schTable.getModel();
        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++) {
            schTable.getColumnModel().getColumn(columnIndex).setCellRenderer(renderer);
        }
        renderer = (DefaultTableCellRenderer) schTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        leftSidePanel = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        weekBox = new javax.swing.JComboBox<>();
        rightSidePanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        privLabel = new javax.swing.JLabel();
        midPanel = new javax.swing.JPanel();
        totalGames = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        schScrollPane = new javax.swing.JScrollPane();
        schTable = new javax.swing.JTable();
        teamScrollPane = new javax.swing.JScrollPane();
        teamTable = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        superPanel = new javax.swing.JPanel();
        startDateButton = new javax.swing.JButton();
        editTeam = new javax.swing.JButton();
        changeMatchDate = new javax.swing.JButton();
        matchButton = new javax.swing.JButton();
        scoreButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.BorderLayout());

        topPanel.setPreferredSize(new java.awt.Dimension(322, 78));

        leftSidePanel.setLayout(new javax.swing.BoxLayout(leftSidePanel, javax.swing.BoxLayout.Y_AXIS));

        topLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topLabel.setText("Marietta High School Debate Calender");
        topLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        leftSidePanel.add(topLabel);
        leftSidePanel.add(Box.createRigidArea(new Dimension(0, 5)));

        weekBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        weekBox.setAlignmentX(Component.LEFT_ALIGNMENT);
        weekBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekBoxActionPerformed(evt);
            }
        });
        leftSidePanel.add(weekBox);

        rightSidePanel.setLayout(new javax.swing.BoxLayout(rightSidePanel, javax.swing.BoxLayout.PAGE_AXIS));

        loginButton.setText("Admin Login");
        loginButton.setAlignmentX(Component.RIGHT_ALIGNMENT);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        rightSidePanel.add(loginButton);

        loginLabel.setText("   ");
        loginLabel.setAlignmentX(Component.RIGHT_ALIGNMENT);
        rightSidePanel.add(loginLabel);

        privLabel.setText("   ");
        privLabel.setAlignmentX(Component.RIGHT_ALIGNMENT);
        rightSidePanel.add(privLabel);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 838, Short.MAX_VALUE)
                .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(topPanel, java.awt.BorderLayout.PAGE_START);

        totalGames.setText("Total Games: 0");

        tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        schTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Match Number", "First Team", "Second Team", "First Team Score", "Second Team Score", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        schTable.setRowHeight(50);
        schTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        schScrollPane.setViewportView(schTable);

        tabs.addTab("Schedule", schScrollPane);

        teamTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team Name", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teamTable.setAutoscrolls(false);
        teamTable.setRowHeight(50);
        teamScrollPane.setViewportView(teamTable);

        tabs.addTab("Total Score", teamScrollPane);

        javax.swing.GroupLayout midPanelLayout = new javax.swing.GroupLayout(midPanel);
        midPanel.setLayout(midPanelLayout);
        midPanelLayout.setHorizontalGroup(
            midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(midPanelLayout.createSequentialGroup()
                        .addComponent(totalGames)
                        .addGap(0, 1168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        midPanelLayout.setVerticalGroup(
            midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalGames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
        );

        add(midPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new java.awt.Dimension(423, 48));

        superPanel.setLayout(new javax.swing.BoxLayout(superPanel, javax.swing.BoxLayout.X_AXIS));

        startDateButton.setText("Set Start Date");
        startDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateButtonActionPerformed(evt);
            }
        });
        superPanel.add(startDateButton);
        superPanel.add(Box.createRigidArea(new Dimension(10, 0)));

        editTeam.setText("Setup Teams");
        editTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTeamActionPerformed(evt);
            }
        });
        superPanel.add(editTeam);
        superPanel.add(Box.createRigidArea(new Dimension(10, 0)));

        changeMatchDate.setText("Change Match Date");
        changeMatchDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMatchDateActionPerformed(evt);
            }
        });
        superPanel.add(changeMatchDate);
        superPanel.add(Box.createRigidArea(new Dimension(10, 0)));

        matchButton.setText("Create Schedule");
        matchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchButtonActionPerformed(evt);
            }
        });
        superPanel.add(matchButton);

        scoreButton.setText("Edit Match Score");
        scoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(superPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 635, Short.MAX_VALUE)
                .addComponent(scoreButton)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(superPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreButton))
                .addGap(682, 682, 682))
        );

        add(bottomPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    //========================== DB Setup=======================================
    public void setupDB() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            c1 = DriverManager.getConnection(ABDebatePro.DBURL);
            stmt = c1.createStatement();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void populateDropBox() {
        a.count();
        int noOfTeams = a.count;
        noOfWeeks = 0;
        if (noOfTeams == 2) {
            noOfWeeks = 1;
        }
        if (noOfTeams == 3) {
            noOfWeeks = 3;
        }
        if (noOfTeams == 4) {
            noOfWeeks = 6;
        }
        if (noOfTeams >= 5) {
            noOfWeeks = 10;
        }
        String[] weekBoxString = new String[noOfWeeks + 1];
        weekBoxString[0] = "All Weeks";
        for (int i = 0; i < noOfWeeks; i++) {
            weekBoxString[i + 1] = "Week " + (i + 1);
        }
        weekBox.setModel(new javax.swing.DefaultComboBoxModel<>(weekBoxString));
        weekBox.setSelectedIndex(0);
        loginButton.requestFocusInWindow();
    }
    //========================== Checks Teams From Database ====================
    public void checkTeams() {
        try {
            int count = 0;
            String sql = "SELECT count(*) AS total from Teams";
            PreparedStatement pstmt = c1.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                count = rs.getInt("total");
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No teams are added to the database, please add some teams.", "Error!" + "", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Refresh() {
        /*try {
            Connection c1 = DriverManager.getConnection(DBURL);
            Statement stmt = c1.createStatement();
            ResultSet rs = stmt.executeQuery(sqlStatement);
            DefaultTableModel yourModel = (DefaultTableModel) schTable.getModel();
            yourModel.setRowCount(0);
            while (rs.next()) {
               yourModel = (DefaultTableModel) schTable.getModel();
               yourModel.addRow(new Object[]{rs.getString("MatchNumber"), rs.getString("FirstTeam"), rs.getString("SecondTeam")
                       , rs.getInt("FirstTeamScore"), rs.getInt("SecondTeamScore"), rs.getDate("MatchDate")});
            }
            c1.close();
	} catch (Exception e) {
            System.out.println(e);
	}*/
        try {
            Connection c1 = DriverManager.getConnection(DBURL);
            PreparedStatement pstmt = c1.prepareStatement(sqlStatement);
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel yourModel = (DefaultTableModel) schTable.getModel();
            yourModel.setRowCount(0);
            while (rs.next()) {
                yourModel = (DefaultTableModel) schTable.getModel();
                yourModel.addRow(new Object[]{rs.getString("MatchNumber"), rs.getString("FirstTeam"), rs.getString("SecondTeam"),
                    rs.getInt("FirstTeamScore"), rs.getInt("SecondTeamScore"), rs.getDate("MatchDate")});
            }
            c1.close();
            pstmt.close();
        } catch (Exception e) {
            System.out.println("Error was here:" + e);
        }
        try {
            Connection c1 = DriverManager.getConnection(DBURL);
            Statement stmt = c1.createStatement();
            ResultSet rs = stmt.executeQuery("select Count(MatchNumber) AS TotalNumber from Schedule");
            while (rs.next()) {
                int number = rs.getInt("TotalNumber");
                totalGames.setText("Total Games: " + Integer.toString(number));
            }
            c1.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        //populateDropBox();
    }    //========================== Prompts To Reenter Password ===================
    public void promptPassword() {
        LoginPage lp = new LoginPage(ABDebatePro.ab, true, "Call second constructor");
        lp.setVisible(true);
    }
    private void matchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchButtonActionPerformed
        Teams t1 = new Teams();
        t1.selectAllDB();
        if (t1.getID() == 0) {
            JOptionPane.showMessageDialog(null, "There are no teams, please add some teams!");
        } else {
            if (schTable.getRowCount() > 0) {
                JOptionPane.showMessageDialog(null, "Warning, previous Schedule would be replaced!");
                promptPassword();
                if (LoginPage.accessGrant == true) {
                    a.count();
                    a.makeSch();
                    a.insertSch();
                    populateDropBox();
                    Refresh();
                }
            } else {
                a.count();
                a.makeSch();
                a.insertSch();
                populateDropBox();
                Refresh();
            }
        }
    }//GEN-LAST:event_matchButtonActionPerformed

    private void scoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreButtonActionPerformed
        if (!(schTable.getSelectedRow() == -1)) {
            int scoreOne, scoreTwo;
            scoreOne = (Integer) schTable.getValueAt(schTable.getSelectedRow(), 3);
            scoreTwo = (Integer) schTable.getValueAt(schTable.getSelectedRow(), 4);
            if ((scoreOne == 0 && scoreTwo == 0) || privLabel.getText().equals("Super Referee")) {
                JTextField scoreField = new JTextField(10);
                JTextField scoreField2 = new JTextField(10);
                JPanel myPanel = new JPanel();
                GridLayout layout = new GridLayout(2, 2, 5, 5);
                // two j lables for the edit score button
                myPanel.add(new JLabel("Team " + schTable.getValueAt(schTable.getSelectedRow(), 1) + " Score:"));
                myPanel.add(scoreField);
                myPanel.setLayout(layout);
                myPanel.add(new JLabel("Team " + schTable.getValueAt(schTable.getSelectedRow(), 2) + " Score:"));
                myPanel.add(scoreField2);
                myPanel.setLayout(layout);
                String regex = "[0-9]+";
                int result = JOptionPane.showConfirmDialog(null, myPanel,
                        "Edit Score", JOptionPane.OK_CANCEL_OPTION);
                String score1 = scoreField.getText();
                String score2 = scoreField2.getText();
                if (result == JOptionPane.OK_OPTION) {
                    if (score1.matches(regex) && score2.matches(regex)) {
                        if (Integer.parseInt(score1) >= 0 && Integer.parseInt(score1) < 11 && Integer.parseInt(score2) >= 0 && Integer.parseInt(score2) < 11) {
                            try {
                                Schedule sch = new Schedule();
                                System.out.println(schTable.getSelectedRow() + 1);
                                sch.selectDB(schTable.getSelectedRow() + 1);
                                sch.updateScore(sch.getMatchNumber(), Integer.parseInt(scoreField.getText()), Integer.parseInt(scoreField2.getText()));
                                Teams t1 = new Teams();
                                t1.CalculateTeamScore();
                            } catch (Exception e) {
                                System.out.println(e);
                            } finally {
                                Refresh();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Score should be between 0 and 10!");
                            scoreButton.doClick();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Enter a valid score between 0 and 10!");
                        scoreButton.doClick();
                    }
                }//no else
            } else {
                JOptionPane.showMessageDialog(null, "Only Super Referee is authorized to change scores!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "You need to select a match first!");
        }
    }//GEN-LAST:event_scoreButtonActionPerformed

    private void editTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTeamActionPerformed
        EditTeams et = new EditTeams(ABDebatePro.ab, true);
        et.setVisible(true);
    }//GEN-LAST:event_editTeamActionPerformed

    private void startDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateButtonActionPerformed
        //Calender c = new Calender(ABDebatePro.ab, true);
        //c.setVisible(true);
        //DatePickerSaturdayOnly.frame.setVisible(true);
        //atePickerSaturdayOnly.runAwesome();
        //ABDebatePro.ab.add(DatePickerSaturdayOnly.fxPanel);
        // DatePickerSaturdayOnly.frame.setLocation(500, 250);
        //DatePickerSaturdayOnly.frame.setAlwaysOnTop(true);
        DatePick dp = new DatePick(ABDebatePro.ab, true);
    }//GEN-LAST:event_startDateButtonActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        if (tabs.getSelectedIndex() == 1) {
            try {
                Connection c1 = DriverManager.getConnection(DBURL);
                PreparedStatement pstmt = c1.prepareStatement("select * from Teams Order by TeamScore DESC");
                ResultSet rs = pstmt.executeQuery();
                DefaultTableModel yourModel = (DefaultTableModel) teamTable.getModel();
                yourModel.setRowCount(0);
                while (rs.next()) {
                    yourModel = (DefaultTableModel) teamTable.getModel();
                    yourModel.addRow(new Object[]{rs.getString("TeamName"), rs.getInt("TeamScore")});
                }
                c1.close();
                pstmt.close();
            } catch (Exception e) {
                System.out.println("Error was here:" + e);
            }
        }
    }//GEN-LAST:event_tabsStateChanged

    private void weekBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekBoxActionPerformed
        Dates d1 = new Dates();
        d1.selectDB();
        Calendar cal = Calendar.getInstance();
        cal.setTime(d1.sDate);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //select date from datesch where "somedate" = schdate
        if (weekBox.getSelectedItem().equals("All Weeks")) {
            sqlStatement = "select * from Schedule Order by MatchNumber ASC";
        } else if (weekBox.getSelectedItem().equals("Week 1")) {
            sqlStatement = "select * from Schedule where MatchDate = #" + d1.sDate + "# Order by MatchNumber ASC";
        } else {
            for (int i = 0; i < noOfWeeks; i++) {
                if (weekBox.getSelectedItem().equals("Week " + (i + 2))) {
                    cal.add(Calendar.DATE, 7 * (i + 1));
                    sqlStatement = "select * from Schedule where MatchDate = #" + dateFormat.format(cal.getTime()) + "# Order by MatchNumber ASC";
                    System.out.println("The week you selected is : " + weekBox.getSelectedItem());
                    //weekBox.setSelectedIndex(weekBox.getSelectedItem().);
                }
            }
        }
        /*else if(weekBox.getSelectedItem().equals("Week 2")) {
            cal.add(Calendar.DATE, 7);
            sqlStatement = "select * from Schedule where MatchDate = #" + dateFormat.format(cal.getTime()) + "# Order by MatchNumber ASC";
        } else if(weekBox.getSelectedItem().equals("Week 3")) {
            cal.add(Calendar.DATE, 14);
            sqlStatement = "select * from Schedule where MatchDate = #" + dateFormat.format(cal.getTime()) + "# Order by MatchNumber ASC";
        }*/
        System.out.println("You chose: " + weekBox.getSelectedItem());
        Refresh();
    }//GEN-LAST:event_weekBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if (loginButton.getText().equals("Admin Login")) {
            LoginPage lp = new LoginPage(ABDebatePro.ab, true);
            lp.setVisible(true);
        } else if (loginButton.getText().equals("Logout")) {
            bottomPanel.setVisible(false);
            loginButton.setText("Admin Login");
            loginLabel.setText("");
            privLabel.setText("");
            LoginPage.storeUser = "";
            LoginPage.storePass = "";
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void changeMatchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMatchDateActionPerformed
        if (!(schTable.getSelectedRow() == -1)) {
            DatePick dp = new DatePick(ABDebatePro.ab, true, "Changing Match Date");
        } else {
            JOptionPane.showMessageDialog(null, "You need to select a match first!");
        }
    }//GEN-LAST:event_changeMatchDateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel bottomPanel;
    public static javax.swing.JButton changeMatchDate;
    public static javax.swing.JButton editTeam;
    public static javax.swing.JPanel leftSidePanel;
    public static javax.swing.JButton loginButton;
    public static javax.swing.JLabel loginLabel;
    public static javax.swing.JButton matchButton;
    public static javax.swing.JPanel midPanel;
    public static javax.swing.JLabel privLabel;
    public javax.swing.JPanel rightSidePanel;
    public static javax.swing.JScrollPane schScrollPane;
    public javax.swing.JTable schTable;
    public static javax.swing.JButton scoreButton;
    public static javax.swing.JButton startDateButton;
    public static javax.swing.JPanel superPanel;
    public static javax.swing.JTabbedPane tabs;
    public static javax.swing.JScrollPane teamScrollPane;
    public javax.swing.JTable teamTable;
    public javax.swing.JLabel topLabel;
    public static javax.swing.JPanel topPanel;
    public javax.swing.JLabel totalGames;
    public static javax.swing.JComboBox<String> weekBox;
    // End of variables declaration//GEN-END:variables
}
